// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simplz.DNDBeyondOpenAI.Bot.Data;

#nullable disable

namespace Simplz.DNDBeyondOpenAI.Bot.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Simplz.DNDBeyondOpenAI.Bot.Data.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Simplz.DNDBeyondOpenAI.Bot.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Simplz.DNDBeyondOpenAI.Bot.Data.GameCharacter", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GameCharacters");
                });

            modelBuilder.Entity("Simplz.DNDBeyondOpenAI.Bot.Data.GameCharacter", b =>
                {
                    b.HasOne("Simplz.DNDBeyondOpenAI.Bot.Data.Character", "Character")
                        .WithMany("GameCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Simplz.DNDBeyondOpenAI.Bot.Data.Game", "Game")
                        .WithMany("GameCharacters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Simplz.DNDBeyondOpenAI.Bot.Data.Character", b =>
                {
                    b.Navigation("GameCharacters");
                });

            modelBuilder.Entity("Simplz.DNDBeyondOpenAI.Bot.Data.Game", b =>
                {
                    b.Navigation("GameCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
